# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm8450-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cupid marble mayfly mondrian thor unicorn zeus ziyi,$(TARGET_DEVICE)),)

endif
