# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm8450-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cupid dagda diting marble mayfly mondrian taranis thor unicorn zeus ziyi zizhan,$(TARGET_DEVICE)),)

endif
